# config.pyi
from typing import Dict, Tuple, List

functionsName: Dict[str, str] = ...
functions: Dict[str, object] = ...
functions_bad: Dict[str, bool] = ...

saveThePath: str = ...

error_list_a1: Tuple[ModuleNotFoundError, TypeError, ImportError, FileNotFoundError, ModuleNotFoundError] = ...
error_list_a2: Tuple[TypeError, Exception] = ...
error_all: Tuple[Exception] = ...

config_type_tuple: Tuple[type, ...] = ...
screening: Tuple[str, ...] = ...

path: List[str] = ...

multithreading: bool = ...
numberOfThreads: int = ...